---
- name: Set SELinux to enforcing
  hosts: localhost
  gather_facts: false
  become: true
  tasks:
    - name: Set SELinux to enforcing
      ansible.posix.selinux:
        policy: targeted
        state: enforcing
