---
- name: Configure firewall rules
  hosts: ansible1
  become: true
  vars:
    # Define services with their desired states and zones
    firewall_services:
      - name: ssh
        state: enabled
        zone: public
      - name: http
      - name: https
        state: disabled
      - name: dns
        zone: internal
  tasks:
    - name: Ensure default state for services if not specified
      ansible.builtin.set_fact:
        firewall_services: >-
          {{
            firewall_services | map('combine', {'state': 'enabled'}) | list
          }}
    - name: Configure firewall services
      ansible.posix.firewalld:
        service: "{{ item.name }}"
        state: "{{ item.state }}"
        zone: "{{ item.zone | default(omit) }}"
        immediate: true
        permanent: true
      loop: "{{ firewall_services }}"
    - name: Debug output of configured firewall services
      ansible.builtin.debug:
        msg: "Service {{ item.name }} is set to {{ item.state }} in zone {{ item.zone | default('not specified')
          }}"
      loop: "{{ firewall_services }}"
