---
- name: Create user with encrypted pass
  hosts: ansible2
  gather_facts: false
  vars_prompt:
    - name: passw
      prompt: which password do you want to use
      private: false
  vars:
    user: sharon
  tasks:
    - name: Set up a password
      ansible.builtin.debug:
        msg: "{{ '{{ passw }}' | password_hash('sha512','myrandomsalt') }}"  # noqa: jinja[spacing]
      register: mypass
    - name: Print the password
      ansible.builtin.debug:
        var: mypass
    - name: Create the user with the above password
      user:
        name: '{{ user }}'
        password: '{{ mypass.msg }}'
