---
- name: demonstrate custom filter
  hosts: localhost
  gather_facts: false
  vars:
    number: '1223456'
  tasks:
    - name: Print the phone number formatted in US style
      ansible.builtin.debug:
        msg: the number is {{ number | my_namespace.my_collection.phone_format }}
