---
- name: Example Playbook Using selectattr Filter
  hosts: localhost
  gather_facts: false
  vars:
    users:
      - name: alice
        active: true
        role: admin
      - name: bob
        active: false
        role: user
      - name: caroline
        active: true
        role: user
      - name: diana
        active: false
        role: guest
  tasks:
    - name: Filter active users
      ansible.builtin.set_fact:
        active_users: "{{ users | selectattr('active', 'equalto', true) | list }}"
    - name: Display active users
      ansible.builtin.debug:
        var: active_users
    - name: Filter inactive users
      ansible.builtin.set_fact:
        inactive_users: "{{ users | selectattr('active', 'equalto', false) | list }}"
    - name: Display inactive users
      ansible.builtin.debug:
        var: inactive_users
    - name: Filter users by role 'user'
      ansible.builtin.set_fact:
        user_role_users: "{{ users | selectattr('role', 'equalto', 'user') | list }}"
    - name: Display users with role 'user'
      ansible.builtin.debug:
        var: user_role_users
