---
- name: Use templates to provide the right language
  hosts: all
  gather_facts: false
  vars:
    language: "{{ lookup('env','LANG') | default('en_US.UTF-8') }}"
  tasks:
    - name: Install motd in the right language  # noqa: risky-file-permissions
      ansible.builtin.copy:
        content: "{{ lookup('template', 'motd.' + language + '.j2') }}"
        dest: /etc/motd
