---
- name: Create users with random passwords
  hosts: all
  gather_facts: false
  vars:
    mypassword: "{{ lookup('password', 'credentials/' + item + ' length=6') }}"
  tasks:
    - name: Loop over and print passwords
      ansible.builtin.debug:
        msg: random password {{ mypassword }} for user {{ item }}
      loop: "{{ query('lines', 'cat users.txt') }}"
    - name: Set up users with passwords
      ansible.builtin.user:
        name: "{{ item }}"
        password: "{{ mypassword | password_hash('sha512') }}"
        update_password: on_create
      loop: "{{ query('lines', 'cat users.txt') }}"
