---
- name: Create users on localhost
  hosts: localhost
  vars_files: [exercise134-vars.yaml]
  tasks:
    - name: Include user and group setup
      import_tasks: exercise134-tasks.yaml
    - name: Create a directory to store the file  # noqa: risky-file-permissions
      ansible.builtin.file:
        name: '{{ item.username }}'
        state: directory
      loop: '{{ users }}'
    - name: Copy the local user ssh key to temporary {{ item.username }} key  # noqa: no-changed-when
      ansible.builtin.shell: cat /home/{{ item.username }}/.ssh/id_rsa.pub >| {{ item.username }}/id_rsa.pub
      loop: '{{ users }}'
    - name: Verify that file exists  # noqa: no-changed-when
      ansible.builtin.command: ls -l {{ item.username }}/
      loop: '{{ users }}'
  tags: setuplocal
- name: create users on managed host
  hosts: ansible1
  vars_files: [exercise134-vars.yaml]
  tasks:
    - name: Include user and group setup
      import_tasks: exercise134-tasks.yaml
    - name: Copy authorized keys
      authorized_key:
        user: '{{ item.username }}'
        key: "{{ lookup('file', './' + item.username + '/id_rsa.pub') }}"
      loop: '{{ users }}'
    - name: Copy sudoers file  # noqa: risky-file-permissions
      copy:
        content: '%admins ALL=(ALL:ALL) NOPASSWD:ALL'
        dest: /etc/sudoers.d/admins
  tags: setupremote
