---
- name: Assert example with sizes
  hosts: localhost
  gather_facts: false
  vars_prompt:
    - name: filesize
      prompt: specify a file size in megabytes
      private: false
  tasks:
    - name: Check if file size is valid
      ansible.builtin.assert:
        that: [(filesize | int) <= 100, (filesize | int) >= 1]
        fail_msg: file size must be between 0 and 100
        success_msg: file size is good, lets continue
    - name: Create a file  # noqa no-changed-when
      ansible.builtin.command: dd if=/dev/zero of=/bigfile bs=1 count={{ filesize }}
