---
- name: Sample of stat and assert
  hosts: ansible2
  gather_facts: false
  tasks:
    - name: Stat a directory
      ansible.builtin.stat:
        # path: /etc/hosts
        path: /etc
      register: sta
    - name: Assert that the filesystem entity stat'ed is a directory
      ansible.builtin.assert:
        that: sta.stat.isdir
