---
- name: Simple block example
  hosts: all
  tasks:
    - name: Setting up http
      # when: ansible_distribution == "RedHat"
      when: ansible_os_family == "RedHat"
      block:
        - name: Installing http
          ansible.builtin.dnf:
            name: httpd
            state: present
        - name: Restart httpd
          ansible.builtin.service:
            name: httpd
            state: started
