---
- name: Find config
  hosts: localhost
  # become: true
  tasks:
    - name: Find ansible.cfg files
      ansible.builtin.find:
        paths: /home/ansible/rhce8-live
        patterns: ansible.cfg
        recurse: true
      register: output
    - name: Print item path
      ansible.builtin.debug:
        var: item.path
      with_items: '{{ output.files }}'
    - name: Add content to file
      ansible.builtin.blockinfile:
        path: '{{ item.path }}'
        insertafter: defaults
        marker: '##<!-- {mark} ANSIBLE MANAGED BLOCK -->##'
        block: |
          fact_caching = redis
          fact_caching_timeout = 3600
          fact_caching_connection = localhost:6379:0
      with_items: '{{ output.files }}'
