---
- name: Demonstrating failed_when
  # hosts: all
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Showing failure  # noqa no-changed-when
      ansible.builtin.command: echo hello world
      ignore_errors: true
      register: command_result
      failed_when: "'world' in command_result.stdout"  # just to simulate a failure
      # failed_when: "'world' in command_result.stdout"
    - name: See if we get here
      ansible.builtin.debug:
        msg: hello
