---
- name: set up web server
  # hosts: all
  hosts: ansible1
  gather_facts: false
  force_handlers: true
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: present
    - name: copy index.html  # noqa risky-file-permissions
      copy:
        src: ./index.html
        dest: /var/www/html/index.html
      notify: [restart_web]
    - name: copy nothing - intended to fail  # noqa risky-file-permissions
      copy:
        src: /tmp/nothing
        dest: /var/www/html/nothing.html
  handlers:
    - name: restart_web
      service:
        name: httpd
        state: restarted
