---
- name: Update /tmp/hosts file dynamically
  hosts: all
  tasks:
    - name: Update /etc/hosts  # noqarisky-file-permissions
      ansible.builtin.template:
        src: ./hosts.j2
        dest: /tmp/hosts
