---
- name: IP address example play
  hosts: all
  gather_facts: true
  tasks:
    - name: show IP address
      debug:
        msg: >-
          This host uses IP address {{ ansible_facts.default_ipv4.address }}
