---
- name: IP address example play
  hosts: all
  gather_facts: true
  tasks:
    - name: show IP address
      ansible.builtin.debug:
        msg: >-
          This host uses IP address {{ ansible_facts.default_ipv4.address }}
    - name: Pre 2.5 notation
      ansible.builtin.debug:
        msg: >-
          This host uses IP address {{ ansible_default_ipv4.address }}
    - name: Current notation
      ansible.builtin.debug:
        msg: >-
          This host uses IP address {{ ansible_facts['default_ipv4']['address'] }}
