---
- name: Idempotent command lab 07
  gather_facts: false
  hosts: ansible1
  ignore_errors: true
  tasks:
    - name: Add a user  # noqa no-changed-when
      ansible.builtin.command: useradd joan
      register: addeduser
    - name: Run an assertion
      ansible.builtin.assert:
        that: [addeduser.rc == 9]
        success_msg: user already exists, but that is okay because we are now idempotent
    - name: Check that end of playbook is reached
      ansible.builtin.debug:
        # var: addeduser
        msg: Reached end of playbook!
