---
- name: Administering a web package on all systems
  gather_facts: false
  hosts: all
  tasks:
    - name: Administering {{ web_package }}
      ansible.builtin.package:
        name: '{{ web_package }}'
        # state: present
        state: absent
    # - name: Enable and start {{ web_service }}
    #   ansible.builtin.service:
    #     name: '{{ web_service }}'
    #     state: started
    #     enabled: true
