---
- name: Demonstrate loop 3
  hosts: localhost
  gather_facts: false
  vars_files: [usernames]
  tasks:
    - name: Show some looping
      ansible.builtin.debug:
        msg: 'User {{ item.name }} belongs to following group(s): {{ item.groups }}'
      loop: '{{ myusers }}'
