---
- name: Demonstrate loop 2
  hosts: localhost
  gather_facts: false
  vars_files: [loop_vars]
  tasks:
    - name: Show some looping
      ansible.builtin.debug:
        msg: '{{ item }}'
      loop: '{{ myitems }}'
