---
- name: demo the register facility
  hosts: ansible1
  # hosts: localhost
  gather_facts: false
  tasks:
    - name: Run the date command  # noqa: no-changed-when
      ansible.builtin.command: date
      register: thisdate
    - name: Show the contents of the register variable
      debug:
        # var: thisdate
        msg: >-
          The date is {{ thisdate['stdout'] }}
