---
- name: demo the register facility
  hosts: ansible1
  tasks:
    - name: Show the date
      ansible.builtin.command: date
      register: thisdate
    - name: Show the contents of the register variable
      debug:
        var: thisdate
