---
- name: set_fact demo
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Setting host facts
      ansible.builtin.set_fact:
        myfirstfact: saturday
        mysecondfact: evening
    - name: Print facts set through set_fact
      ansible.builtin.debug:
        msg: Typing this on {{ myfirstfact }} {{ mysecondfact }}
- name: New play
  hosts: localhost
  tasks:
    - name: Prove that set_facts are global across playbook
      ansible.builtin.debug:
        msg: It is still {{ myfirstfact }} {{ mysecondfact }}
