---
- name: Variables demo
  gather_facts: false
  vars:
    myuser: anna
  hosts: all
  tasks:
    - name: Creating user {{ myuser }}
      ansible.builtin.user:
        name: '{{ myuser }}'
        shell: /bin/bash
