---
- name: using multiple conditions
  hosts: all
  tasks:
    - name: Install httpd
      package:
        name: httpd
        state: installed
      when: [ansible_distribution == "RedHat", ansible_memfree_mb > 512]
